import { useState } from 'react';
import EvidenceIds from '@/components/EvidenceIds';
import { EmptyState } from '@/components/States';
import { formatConfidence, formatDateTime, stageLabel } from '@/utils/format';
import type { InvestigationResponse, InvestigationReport } from '@/types';

type Section = 'summary' | 'threat' | 'narrative' | 'findings' | 'evidence' | 'uncertainties' | 'steps';

const SECTIONS: { key: Section; label: string }[] = [
  { key: 'summary', label: 'Summary' },
  { key: 'threat', label: 'Threat' },
  { key: 'narrative', label: 'Narrative' },
  { key: 'findings', label: 'Findings' },
  { key: 'evidence', label: 'Evidence' },
  { key: 'uncertainties', label: 'Uncertainties' },
  { key: 'steps', label: 'Next Steps' },
];

export default function InvestigationPanel({
  investigation,
  running,
  error,
  onRun,
  disabled,
}: {
  investigation: InvestigationResponse | null;
  running: boolean;
  error: string | null;
  onRun: () => void;
  disabled: boolean;
}) {
  const report = investigation?.investigation;
  const isDemo = investigation?.analysis_mode?.toUpperCase().includes('DEMO') ?? false;
  const [activeSection, setActiveSection] = useState<Section>('summary');

  return (
    <section className="panel" data-testid="investigation-panel">
      <div
        style={{
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'space-between',
          gap: 12,
          flexWrap: 'wrap',
          marginBottom: 14,
        }}
      >
        <h2 className="panel-title" style={{ marginBottom: 0 }}>
          AI Investigation
        </h2>
        <div style={{ display: 'flex', gap: 10, alignItems: 'center' }}>
          {investigation ? (
            <span className={`badge ${isDemo ? 'badge-demo' : 'badge-live'}`} data-testid="investigation-mode">
              {isDemo ? 'DEMO MODE' : 'LIVE LLM'}
            </span>
          ) : null}
          <button
            type="button"
            className="btn btn-primary"
            onClick={onRun}
            disabled={disabled || running}
            data-testid="investigate-button"
          >
            {running ? 'Investigating...' : investigation ? 'Re-run Investigation' : 'Investigate Incident'}
          </button>
        </div>
      </div>

      {isDemo ? (
        <div className="notice notice-warn" data-testid="demo-notice">
          DEMO MODE -- this investigation was generated by the deterministic mock provider, not a
          live LLM. Findings are illustrative.
        </div>
      ) : null}

      {error ? (
        <div className="error-banner" role="alert" data-testid="investigation-error">
          <span aria-hidden="true">!</span>
          <span>{error}</span>
        </div>
      ) : null}

      {!report ? (
        <EmptyState
          title="No investigation run yet"
          hint="Click Investigate Incident to run the AI investigation."
        />
      ) : (
        <InvestigationBody
          report={report}
          investigation={investigation}
          activeSection={activeSection}
          setActiveSection={setActiveSection}
        />
      )}
    </section>
  );
}

function InvestigationBody({
  report,
  investigation,
  activeSection,
  setActiveSection,
}: {
  report: InvestigationReport;
  investigation: InvestigationResponse;
  activeSection: Section;
  setActiveSection: (s: Section) => void;
}) {
  return (
    <div>
      <div className="meta-line" style={{ marginBottom: 14 }}>
        <span>Provider: <b>{investigation.provider}</b></span>
        <span>Generated: {formatDateTime(investigation.generated_at)}</span>
        <span>Confidence: <b>{formatConfidence(report.confidence)}</b></span>
        {investigation.context_truncated ? (
          <span className="badge badge-neutral">context truncated</span>
        ) : null}
      </div>

      <div className="inv-section-tabs" data-testid="investigation-section-tabs">
        {SECTIONS.map((s) => (
          <button
            key={s.key}
            type="button"
            className={`inv-tab ${activeSection === s.key ? 'inv-tab-active' : ''}`}
            onClick={() => setActiveSection(s.key)}
          >
            {s.label}
          </button>
        ))}
      </div>

      <div data-testid="investigation-section-content">
        {activeSection === 'summary' && <ExecutiveSummarySection report={report} />}
        {activeSection === 'threat' && <ThreatAssessmentSection report={report} />}
        {activeSection === 'narrative' && <AttackNarrativeSection report={report} />}
        {activeSection === 'findings' && <FindingsSection report={report} />}
        {activeSection === 'evidence' && <EvidenceSection report={report} />}
        {activeSection === 'uncertainties' && <UncertaintiesSection report={report} />}
        {activeSection === 'steps' && <NextStepsSection report={report} />}
      </div>
    </div>
  );
}

function ExecutiveSummarySection({ report }: { report: InvestigationReport }) {
  return (
    <div className="inv-section" data-testid="investigation-summary">
      <div className="inv-section-header">
        <h3 className="panel-title" style={{ marginBottom: 0 }}>Executive Summary</h3>
        <span className="badge badge-neutral">{report.evidence.length} evidence items</span>
      </div>
      <p className="inv-body-text">{report.incident_summary}</p>
      {report.affected_entities.length > 0 ? (
        <div style={{ marginTop: 12 }}>
          <span style={{ fontSize: 12, color: 'var(--text-dim)', fontWeight: 600, textTransform: 'uppercase' }}>
            Affected Entities
          </span>
          <div style={{ display: 'flex', gap: 6, flexWrap: 'wrap', marginTop: 6 }}>
            {report.affected_entities.map((entity) => (
              <span key={entity} className="badge badge-info mono" style={{ fontSize: 11 }}>
                {entity}
              </span>
            ))}
          </div>
        </div>
      ) : null}
    </div>
  );
}

function ThreatAssessmentSection({ report }: { report: InvestigationReport }) {
  const confidence = report.confidence ?? 0;
  const confidenceColor =
    confidence >= 0.7 ? 'var(--success)' : confidence >= 0.4 ? 'var(--warning)' : 'var(--critical)';

  return (
    <div className="inv-section" data-testid="investigation-threat">
      <div className="inv-section-header">
        <h3 className="panel-title" style={{ marginBottom: 0 }}>Threat Assessment</h3>
      </div>
      <p className="inv-body-text">{report.threat_assessment}</p>

      <div className="inv-metric-row">
        <div className="inv-metric">
          <span className="inv-metric-label">Confidence</span>
          <div className="confidence-bar" style={{ width: 120 }}>
            <div
              className="confidence-fill"
              style={{ width: `${confidence * 100}%`, background: confidenceColor }}
            />
          </div>
          <span className="mono" style={{ fontWeight: 600, fontSize: 13 }}>
            {formatConfidence(confidence)}
          </span>
        </div>
        <div className="inv-metric">
          <span className="inv-metric-label">Evidence Items</span>
          <span className="mono" style={{ fontWeight: 600, fontSize: 18 }}>
            {report.evidence.length}
          </span>
        </div>
        <div className="inv-metric">
          <span className="inv-metric-label">Findings</span>
          <span className="mono" style={{ fontWeight: 600, fontSize: 18 }}>
            {report.investigation_findings.length}
          </span>
        </div>
      </div>

      {report.potential_attack_stages.length > 0 ? (
        <div style={{ marginTop: 14 }} data-testid="investigation-stages">
          <span style={{ fontSize: 12, color: 'var(--text-dim)', fontWeight: 600, textTransform: 'uppercase' }}>
            Attack Stages
          </span>
          <div className="inv-attack-chain" style={{ marginTop: 8 }}>
            {report.potential_attack_stages.map((stage, i) => (
              <div key={stage} className="inv-chain-step">
                <div className="inv-chain-badge">
                  {stageLabel(stage)}
                </div>
                {i < report.potential_attack_stages.length - 1 ? (
                  <div className="inv-chain-arrow" aria-hidden="true">&#8595;</div>
                ) : null}
              </div>
            ))}
          </div>
        </div>
      ) : null}
    </div>
  );
}

function AttackNarrativeSection({ report }: { report: InvestigationReport }) {
  const narrative = report.attack_narrative;
  const sentences = narrative.split(/(?<=\.)\s+/).filter((s) => s.trim().length > 0);

  return (
    <div className="inv-section" data-testid="investigation-narrative">
      <div className="inv-section-header">
        <h3 className="panel-title" style={{ marginBottom: 0 }}>Attack Narrative</h3>
      </div>
      <div className="inv-narrative">
        {sentences.map((sentence, i) => (
          <div key={i} className="inv-narrative-step">
            <div className="inv-narrative-num">{i + 1}</div>
            <p style={{ color: 'var(--text-muted)', margin: 0, fontSize: 13, lineHeight: 1.6 }}>
              {sentence}
            </p>
          </div>
        ))}
      </div>
    </div>
  );
}

function FindingsSection({ report }: { report: InvestigationReport }) {
  if (report.investigation_findings.length === 0) {
    return (
      <div className="inv-section">
        <EmptyState title="No findings" hint="No investigation findings were generated." />
      </div>
    );
  }

  return (
    <div className="inv-section" data-testid="investigation-findings">
      <div className="inv-section-header">
        <h3 className="panel-title" style={{ marginBottom: 0 }}>Key Findings</h3>
        <span className="badge badge-neutral">{report.investigation_findings.length} findings</span>
      </div>
      <div className="inv-findings-list">
        {report.investigation_findings.map((finding, i) => (
          <div className="inv-finding-card" key={i}>
            <div className="inv-finding-header">
              <span className="inv-finding-num">{String(i + 1).padStart(2, '0')}</span>
              <span style={{ fontWeight: 600, fontSize: 14 }}>{finding.title}</span>
            </div>
            <p style={{ color: 'var(--text-muted)', margin: '6px 0', fontSize: 13, lineHeight: 1.6 }}>
              {finding.detail}
            </p>
            {finding.evidence_ids.length > 0 ? (
              <div style={{ marginTop: 4 }}>
                <EvidenceIds ids={finding.evidence_ids} />
              </div>
            ) : null}
          </div>
        ))}
      </div>
    </div>
  );
}

function EvidenceSection({ report }: { report: InvestigationReport }) {
  if (report.evidence.length === 0) {
    return (
      <div className="inv-section">
        <EmptyState title="No evidence" hint="No evidence items were recorded." />
      </div>
    );
  }

  return (
    <div className="inv-section">
      <div className="inv-section-header">
        <h3 className="panel-title" style={{ marginBottom: 0 }}>Evidence &amp; Citations</h3>
        <span className="badge badge-neutral">{report.evidence.length} items</span>
      </div>
      <div className="table-wrap" data-testid="investigation-evidence-table">
        <table>
          <thead>
            <tr>
              <th style={{ width: 40 }}>#</th>
              <th>Description</th>
              <th style={{ width: 180 }}>Evidence IDs</th>
            </tr>
          </thead>
          <tbody>
            {report.evidence.map((item, i) => (
              <tr key={i}>
                <td className="mono" style={{ color: 'var(--text-dim)' }}>{i + 1}</td>
                <td style={{ color: 'var(--text-muted)', fontSize: 13 }}>{item.description}</td>
                <td>
                  <EvidenceIds ids={item.evidence_ids} />
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  );
}

function UncertaintiesSection({ report }: { report: InvestigationReport }) {
  return (
    <div className="inv-section" data-testid="investigation-uncertainties">
      <div className="inv-section-header">
        <h3 className="panel-title" style={{ marginBottom: 0 }}>Uncertainties &amp; Limitations</h3>
      </div>
      <div className="inv-uncertainties">
        {report.uncertainties.map((item, i) => (
          <div key={i} className="inv-uncertainty-item">
            <span className="inv-uncertainty-icon" aria-hidden="true">!</span>
            <span style={{ color: 'var(--text-muted)', fontSize: 13 }}>{item}</span>
          </div>
        ))}
      </div>
    </div>
  );
}

function NextStepsSection({ report }: { report: InvestigationReport }) {
  if (report.recommended_next_steps.length === 0) {
    return (
      <div className="inv-section">
        <EmptyState title="No next steps" hint="No analyst actions were recommended." />
      </div>
    );
  }

  return (
    <div className="inv-section" data-testid="investigation-next-steps">
      <div className="inv-section-header">
        <h3 className="panel-title" style={{ marginBottom: 0 }}>Analyst Next Steps</h3>
        <span className="badge badge-neutral">{report.recommended_next_steps.length} actions</span>
      </div>
      <div className="inv-steps-list">
        {report.recommended_next_steps.map((step, i) => {
          const isImmediate = step.toUpperCase().startsWith('IMMEDIATE');
          return (
            <div key={i} className={`inv-step ${isImmediate ? 'inv-step-urgent' : ''}`}>
              <div className="inv-step-num">{String(i + 1).padStart(2, '0')}</div>
              <div style={{ flex: 1 }}>
                {isImmediate ? (
                  <span className="badge badge-critical" style={{ fontSize: 10, marginBottom: 4, display: 'inline-block' }}>
                    IMMEDIATE
                  </span>
                ) : null}
                <p style={{ color: 'var(--text-muted)', margin: 0, fontSize: 13, lineHeight: 1.6 }}>
                  {isImmediate ? step.replace(/^IMMEDIATE:\s*/i, '') : step}
                </p>
              </div>
            </div>
          );
        })}
      </div>
    </div>
  );
}
