import type {
  Alert,
  Incident,
  IncidentReport,
  IncidentSummary,
  InvestigationResponse,
  MLStatus,
  RecommendationsResponse,
  SecurityEvent,
} from '@/types';

export const INCIDENT_ID = 'inc-0001-abcd1234';

export const incident: Incident = {
  id: INCIDENT_ID,
  title: 'Correlated attack: brute force to exfiltration',
  severity: 'critical',
  description: 'Multi-stage attack detected on ws-042',
  status: 'open',
  alert_ids: ['alert-1', 'alert-2', 'alert-3'],
  alert_count: 3,
  correlation_score: 0.87,
  correlation_reasons: ['shared source IP', 'shared host'],
  first_seen: '2026-09-01T10:00:00Z',
  last_seen: '2026-09-01T10:12:00Z',
  source_ips: ['185.220.101.5'],
  destination_ips: ['198.51.100.7'],
  users: ['admin'],
  hosts: ['ws-042'],
  risk_score: 62.8,
  risk_level: 'HIGH',
  risk_factors: ['critical severity', 'credential access stage'],
  attack_stages: [
    'Potential stage: Credential Access',
    'Potential stage: Privilege Escalation',
    'Potential stage: Exfiltration',
  ],
  created_at: '2026-09-01T10:12:05Z',
  updated_at: '2026-09-01T10:12:05Z',
};

export const alerts: Alert[] = [
  {
    id: 'alert-1',
    event_id: 'event-1',
    rule_id: 'rule-login',
    rule_name: 'Multiple Failed Logins',
    severity: 'high',
    description: '11 failed SSH logins for admin from 185.220.101.5',
    status: 'new',
    detection_source: 'rule',
    created_at: '2026-09-01T10:00:00Z',
  },
  {
    id: 'alert-2',
    event_id: 'event-2',
    rule_id: 'rule-sudo',
    rule_name: 'Privilege Escalation via Sudo',
    severity: 'critical',
    description: 'admin escalated from viewer to root',
    status: 'new',
    detection_source: 'rule',
    created_at: '2026-09-01T10:07:00Z',
  },
  {
    id: 'alert-3',
    event_id: 'event-3',
    rule_id: 'rule-transfer',
    rule_name: 'Large Data Transfer',
    severity: 'critical',
    description: '2 GB transferred to 198.51.100.7',
    status: 'new',
    detection_source: 'ml',
    created_at: '2026-09-01T10:12:00Z',
  },
];

export const incidentSummary: IncidentSummary = {
  incident,
  risk: {
    incident_id: INCIDENT_ID,
    risk_score: 62.8,
    risk_level: 'HIGH',
    contributing_factors: ['Critical-severity alerts present', 'Credential access stage observed'],
    scoring_explanation:
      'Base 40 for critical severity + 12 for credential-access stage + 10.8 for multiple affected entities.',
  },
  timeline: {
    incident_id: INCIDENT_ID,
    first_seen: '2026-09-01T10:00:00Z',
    last_seen: '2026-09-01T10:12:00Z',
    duration_seconds: 720,
    entries: [
      {
        timestamp: '2026-09-01T10:00:00Z',
        event_id: 'event-1',
        alert_id: 'alert-1',
        event_type: 'failed_login',
        source_ip: '185.220.101.5',
        destination_ip: null,
        user: 'admin',
        host: 'ws-042',
        severity: 'high',
        detection_method: 'rule',
        description: '11 failed SSH logins',
        stage: 'Potential stage: Credential Access',
      },
      {
        timestamp: '2026-09-01T10:07:00Z',
        event_id: 'event-2',
        alert_id: 'alert-2',
        event_type: 'privilege_escalation',
        source_ip: '185.220.101.5',
        destination_ip: null,
        user: 'admin',
        host: 'ws-042',
        severity: 'critical',
        detection_method: 'rule',
        description: 'viewer → root via sudo',
        stage: 'Potential stage: Privilege Escalation',
      },
      {
        timestamp: '2026-09-01T10:12:00Z',
        event_id: 'event-3',
        alert_id: 'alert-3',
        event_type: 'data_transfer',
        source_ip: '185.220.101.5',
        destination_ip: '198.51.100.7',
        user: 'admin',
        host: 'ws-042',
        severity: 'critical',
        detection_method: 'ml',
        description: '2 GB exfiltrated',
        stage: 'Potential stage: Exfiltration',
      },
    ],
  },
  potential_attack_stages: incident.attack_stages,
  related_alert_ids: incident.alert_ids,
};

export const investigation: InvestigationResponse = {
  incident_id: INCIDENT_ID,
  provider: 'demo',
  analysis_mode: 'DEMO (deterministic mock provider - not a live LLM)',
  generated_at: '2026-09-01T10:15:00Z',
  investigation: {
    incident_summary: 'Three correlated alerts spanning 12 minutes on host ws-042.',
    threat_assessment: 'Consistent with credential compromise followed by data exfiltration.',
    evidence: [
      { description: '11 failed logins for admin', evidence_ids: ['alert-alert-1', 'event-event-1'] },
      { description: 'Privilege escalation to root', evidence_ids: ['alert-alert-2'] },
    ],
    attack_narrative: 'Brute force succeeded, privileges escalated, then 2 GB was exfiltrated.',
    potential_attack_stages: ['Credential Access', 'Privilege Escalation', 'Exfiltration'],
    affected_entities: ['admin', 'ws-042'],
    investigation_findings: [
      {
        title: 'Account compromise likely',
        detail: '11 failed logins immediately followed by successful sudo escalation.',
        evidence_ids: ['alert-alert-1', 'alert-alert-2'],
      },
      {
        title: 'Large outbound transfer',
        detail: '2 GB transferred to external IP 198.51.100.7.',
        evidence_ids: ['alert-alert-3', 'event-event-3'],
      },
    ],
    uncertainties: ['No egress firewall logs available to confirm the destination.'],
    recommended_next_steps: ['Reset the admin account credentials', 'Isolate ws-042 from the network'],
    confidence: 0.82,
  },
  evidence_ids: ['alert-alert-1', 'alert-alert-2', 'alert-alert-3', 'event-event-1', 'event-event-2', 'event-event-3'],
  context_truncated: false,
  risk_snapshot: { risk_score: 62.8, risk_level: 'HIGH' },
};

export const recommendations: RecommendationsResponse = {
  incident_id: INCIDENT_ID,
  generated_at: '2026-09-01T10:16:00Z',
  advisory_notice: 'Advisory only: nothing is executed automatically.',
  risk_snapshot: { risk_score: 62.8, risk_level: 'HIGH' },
  recommendation_count: 2,
  recommendations: [
    {
      recommendation_id: 'reco-account',
      title: 'Reset compromised account credentials',
      description: 'Reset the admin account and revoke active sessions.',
      priority: 'CRITICAL',
      priority_score: 100,
      priority_factors: ['critical severity', 'credential access'],
      category: 'containment',
      rationale: 'Critical priority because the incident is HIGH risk (62.8/100).',
      evidence_ids: ['alert-alert-1'],
      confidence: 0.9,
      requires_analyst_approval: true,
    },
    {
      recommendation_id: 'reco-isolate',
      title: 'Isolate affected endpoint',
      description: 'Quarantine ws-042 from the corporate network.',
      priority: 'HIGH',
      priority_score: 78,
      priority_factors: ['exfiltration stage'],
      category: 'containment',
      rationale: 'High priority due to confirmed exfiltration stage.',
      evidence_ids: ['alert-alert-3'],
      confidence: 0.75,
      requires_analyst_approval: true,
    },
  ],
};

export const report: IncidentReport = {
  report_id: 'rep-0001',
  incident_id: INCIDENT_ID,
  generated_at: '2026-09-01T10:17:00Z',
  format_version: '1.0',
  title: 'Incident Report: Correlated attack',
  report_summary: 'Three alerts over 12 minutes indicating a compromised admin account.',
  evidence_references: investigation.evidence_ids,
  observed_evidence: {
    incident: {
      incident_id: INCIDENT_ID,
      title: incident.title,
      status: 'open',
      severity: 'critical',
      description: incident.description ?? null,
      first_seen: incident.first_seen,
      last_seen: incident.last_seen,
      duration_seconds: 720,
      alert_count: 3,
      correlation_score: 0.87,
      correlation_reasons: incident.correlation_reasons,
    },
    affected_users: ['admin'],
    affected_hosts: ['ws-042'],
    source_ips: ['185.220.101.5'],
    destination_ips: ['198.51.100.7'],
    correlated_alerts: [],
    detection_methods: ['rule', 'ml'],
    attack_timeline: { first_seen: incident.first_seen, last_seen: incident.last_seen, duration_seconds: 720, entries: [] },
  },
  analysis: {
    analysis_notice: 'Analysis combines deterministic scoring with advisory AI narrative.',
    deterministic_risk_assessment: { risk_score: 62.8, risk_level: 'HIGH' },
    potential_attack_stages: ['Credential Access', 'Privilege Escalation', 'Exfiltration'],
    ai_investigation: investigation.investigation,
    investigation_metadata: {
      provider: 'demo',
      analysis_mode: investigation.analysis_mode,
      generated_at: investigation.generated_at,
      confidence: 0.82,
    },
    investigation_status: 'completed',
    uncertainties: investigation.investigation.uncertainties,
  },
  recommended_actions: {
    advisory_notice: 'All actions require analyst approval.',
    all_actions_require_analyst_approval: true,
    recommendations: recommendations.recommendations,
  },
};

export const health = {
  status: 'healthy',
  app_name: 'Nexus One',
  version: '1.0.0',
  environment: 'development',
  database: 'connected',
};

export const events: SecurityEvent[] = [
  {
    id: 'event-1',
    source: 'auth-service',
    event_type: 'failed_login',
    severity: 'high',
    payload: {
      src_ip: '185.220.101.5',
      user: 'admin',
      host: 'ws-042',
      failed_attempts: 11,
      action: 'ssh_login',
      outcome: 'failure',
    },
    timestamp: '2026-09-01T10:00:00Z',
    processed: true,
    created_at: '2026-09-01T10:00:01Z',
  },
  {
    id: 'event-2',
    source: 'iam',
    event_type: 'privilege_escalation',
    severity: 'critical',
    payload: {
      src_ip: '185.220.101.5',
      user: 'admin',
      host: 'ws-042',
      old_role: 'viewer',
      new_role: 'root',
      method: 'sudo',
    },
    timestamp: '2026-09-01T10:07:00Z',
    processed: true,
    created_at: '2026-09-01T10:07:01Z',
  },
  {
    id: 'event-3',
    source: 'netflow',
    event_type: 'data_transfer',
    severity: 'critical',
    payload: {
      src_ip: '185.220.101.5',
      dst_ip: '198.51.100.7',
      user: 'admin',
      host: 'ws-042',
      bytes_transferred: 2_147_483_648,
    },
    timestamp: '2026-09-01T10:12:00Z',
    processed: true,
    created_at: '2026-09-01T10:12:01Z',
  },
];

export const mlStatus: MLStatus = {
  model_loaded: true,
  model_path: 'models/isolation_forest.pkl',
  training_samples: 1200,
  features: ['failed_attempts', 'bytes_transferred', 'privilege_flag'],
  threshold: 0.62,
  detection_method: 'isolation_forest',
};
